import yaml


include: "rules/00_modules.smk"
include: "rules/static_env.smk"
include: "rules/functions.smk"
include: "rules/dynamic_env.smk"
include: "rules/utils.smk"
include: "rules/loading.smk"
include: "rules/transforming.smk"
include: "rules/packaging.smk"
include: "rules/data_transformation.smk"


localrules:
    dump_config,


rule run_all:
    input:
        "results/run_config.yaml",
        collect_base_images,
        collect_reference_container_build_targets,


rule dump_config:
    output:
        "results/run_config.yaml",
    run:
        runinfo = {"_timestamp": get_timestamp(), "_username": get_username()}
        runinfo.update(config)
        with open("results/run_config.yaml", "w") as file:
            yaml.dump(runinfo, file)
